[theme]
base = "dark"
primaryColor = "#bd43b8"
secondaryBackgroundColor = "#0c3f4a"
backgroundColor = "#0E1117"        # Streamlit’s default dark background
textColor = "#FAFAFA"              # Clean light text
font = "sans serif"
